spring:
  datasource:
    url: jdbc:postgresql://database:5432/pismo
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 15
  liquibase:
    url: jdbc:postgresql://database:5432/pismo
    password: ${LIQUIBASE_PASSWORD}
