spring:
  datasource:
    url: jdbc:postgresql://database:5432/pismo
    password: ${DATABASE_PASSWORD}
  liquibase:
    contexts: test
    url: jdbc:postgresql://database:5432/pismo
    password: ${LIQUIBASE_PASSWORD}
