server:
  servlet:
    context-path: /transacoes
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

info:
  application: @project.name@
  version: @project.version@

management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      base-path: '/'
      path-mapping:
        health: '/health/check'
        info: '/health/alive'
        prometheus: '/metrics'
      exposure:
        include:
          - info
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 60000

spring:
  profiles:
    active:
      - dev

  datasource:
    username: pismo_system
    name: TransacoesDS
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      register-mbeans: true
      pool-name: TransacoesPool
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      javax.persistence.validation.mode: none
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false

  liquibase:
    change-log: classpath:db/changelog/db_changelog_master.xml
    user: pismo_owner
    driver-class-name: org.postgresql.Driver
    liquibase-schema: public
    test-rollback-on-update: true
